# Generated by Django 4.1.2 on 2022-10-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEAT', '0003_remove_cancion_user_remove_usuario_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='audio',
            new_name='audioPrim',
        ),
        migrations.AddField(
            model_name='cancion',
            name='audioSec',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
