# Generated by Django 4.1.2 on 2022-10-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEAT', '0004_rename_audio_cancion_audioprim_cancion_audiosec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='imagen',
            new_name='imagenPrim',
        ),
        migrations.AddField(
            model_name='cancion',
            name='imagenSec',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
