# Generated by Django 4.1.2 on 2022-10-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BEAT', '0005_rename_imagen_cancion_imagenprim_cancion_imagensec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='audioPrim',
            new_name='Prim',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='imagenPrim',
        ),
    ]
