# Generated by Django 4.1.2 on 2022-11-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEAT', '0007_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='pkU',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
